### ISSUE TITLE
Aligning seat attributes in VSC vs VSS

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_service_catalog#24]
We currently have a seat comfort example service. As of today the semantics is not really aligned with VSS. As an example, in the VSC example we seem to use relative values to describe position (from 0 to 1000). In VSS we use absolute numbers. We should preferably in the future use the same semantics for both, i.e. either absolute in both or relative in both.

Cushion use in VSC relative value:

https://github.com/COVESA/vehicle_service_catalog/blob/master/comfort-service.yml#L65

```
- name: cushion
            datatype: movement_t
            description: |
              The position of the cushion 0 short, 1000 long
```
https://github.com/COVESA/vehicle_signal_specification/blob/05a678095d497d32e6053f444bbaca1ac8bea032/spec/Cabin/SingleSeat.vspec#L81

```
Cushion.Height:
  datatype: uint16
  type: actuator
  min: 0
  unit: mm
  description: Height of the seat cushion (leg support), relative to seat. 0 = Lowermost.
```
